# Generated by Django 6.0 on 2026-01-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
