# Generated by Django 6.0 on 2026-01-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Final_app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
